#global testerror "Err0658"
func main()
{
    return 1
}
