#global testerror "Err0552"

func toto() => "toto"
#error(toto())
