#global testerror "Err0182"

func toto(x: ...)
{
    foreach &a in x
    {
    }
}
