#global testerror "Err0308"
func(N = 6) add()
{
}

#test
{
    add()
}