#global testerror "Err0549"
func toto(x: [4] s32)
{
}

#test
{
	const a = [0,1,2,3]
	toto(a)
}
