#global testerror "Err0034"

func toto() => "coucou"
const A = #include(toto())